### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by rilopez** [rilopez/thermomatic#17]
- [x] create branch spin-master from first commit that is not mine
- [x] create WIP merge request from `master` to `spin-master`
  - [x] create MR description: how to execute scripts, important changes, known issues
- [ ] smock test
   - [x] start server
   - [x] connect two clients
   - [x] verify disconections
   - [x] verify duplicate client
   - [x] verify http reports
      - [x] /stats
      - [x] /status/:imei:
      - [x] /readings/:imei:
 - [x] write email/greenhouse submission 
 - [x] verify  email/greenhouse submission write up
 - [x] add reviewers to repo :
     - `sacabuche` Daniel Robles Pichardo
     - `tjper` Thomas J Perry
     - `radis-spin` Radis Valiullin
 - [x] SHIP IT send  email/greenhouse submission
